# Generated by Django 4.2.3 on 2023-08-09 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fakultet ismi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Fakultet ismi')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Fakultet ismi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Fakultet ismi')),
                ('link_name', models.CharField(max_length=200, verbose_name='fakultet link')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O.')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan kun")),
                ('gender', models.CharField(max_length=10, verbose_name='Jinsi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon nomer')),
                ('course', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kurs')),
                ('image', models.ImageField(upload_to='./image/', verbose_name='Image')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ariza vaqti')),
                ('pasport', models.FileField(blank=True, null=True, upload_to='./pasport/', verbose_name='Passport nusxasi')),
                ('i_va_ii', models.FileField(blank=True, null=True, upload_to='./i_va_ii/', verbose_name='I va II guruh nogiron')),
                ('temir_daftar', models.FileField(blank=True, null=True, upload_to='./temir_daftar/', verbose_name='Temir daftar')),
                ('yetim', models.FileField(blank=True, null=True, upload_to='./yetim/', verbose_name='Yetim')),
                ('yoshlar_daftar', models.FileField(blank=True, null=True, upload_to='./yoshlar/', verbose_name='Yoshlar daftari')),
                ('oila_i_va_ii', models.FileField(blank=True, null=True, upload_to='./oilada_i_va_ii/', verbose_name='Oilasida 1 va 2')),
                ('boshqa', models.FileField(blank=True, null=True, upload_to='./boshqa/', verbose_name='Boshqa imtiyoz')),
                ('commit', models.TextField(blank=True, null=True, verbose_name='Sababi')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculties', verbose_name='Fakultet')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Status')),
            ],
            options={
                'ordering': ['create_at'],
            },
        ),
    ]
