# Generated by Django 4.2.3 on 2023-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='commit',
            field=models.TextField(blank=True, null=True, verbose_name='Sababi'),
        ),
    ]
